# Dependencies
markdown:         kramdown
kramdown:
  math_engine:    mathjax
highlighter:      rouge

# Setup
title:            SonsuzUs
tagline:          'SonsuzUs Programlama ve Yazılım'
description:      'Programlama ve Yazılım'
url:              https://sonsuzus.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
excerpt_separator: "``"
author:
  name:           'Sonsuz Us'
  url:            https://github.com/sonsuzus

paginate:         20
paginate_path:    /page/:num/
                    # Or '/blog/page:num' if you want to move your index pages

defaults:
  - scope:
      path: ""
      type: post
    values:
      permalink: /posts/:title/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-algolia

# Sidebar link settings
sidebar_home_link:  false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
google_analytics : G-JPVWNYQQ08

hydeout:
  repo: https://github.com/sonsuzus/sonsuzus.github.io
  version: 2.0.0

# _config.yml dosyasının sonuna eklenecek
algolia:
  application_id: 'R1ADGRPVAE'
  index_name: 'sonsuzus_notlar'
  search_only_api_key: 'a56052698d8070daa3e26b73f51ff1a4'
